# conda environment description file for the {{ cookiecutter.analysis_repo }} environment
#
# Create a conda environment in which to run Jupyter Notebooks in this directory with:
#
#   $ conda env create -f environment.yaml
#   $ conda activate {{ cookiecutter.analysis_repo }}
#
# To add new packages to the environment,
# add them to the dependencies list below,
# then update the activated environment with:
#
#   ({{ cookiecutter.analysis_repo }})$ conda env update -f environment.yaml

name: {{ cookiecutter.analysis_repo }}

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - bottleneck
  - cartopy
  - cliff
  - cmocean
  - coverage
  - dask
  - f90nml
  - gsw
  - ipdb
  - ipython
  - jupyterlab
  - lxml
  - matplotlib
  - nbsphinx
  - netCDF4
  - numpy
  - openpyxl
  - pandas
  - pillow
  - pip
  - pyproj
  - pytest
  - python=3
  - pytz
  - python-dateutil
  - pyyaml
  - requests
  - retrying
  - scipy
  - shapely
  - sphinx
  - sphinx_rtd_theme
  - tqdm
  - xarray
  
  - pip:
    - angles
