# conda environment description file for the {{ cookiecutter.analysis_repo }} environment
#
# Create a conda environment in which to run Jupyter Notebooks in this directory with:
#
#   $ conda env create -f environment.yaml
#   $ conda activate {{ cookiecutter.analysis_repo }}
#
# To add new packages to the environment,
# add them to the dependencies list below,
# then update the activated environment with:
#
#   ({{ cookiecutter.analysis_repo }})$ conda env update -f environment.yaml

name: {{ cookiecutter.analysis_repo }}

channels:
  - conda-forge
  - defaults

dependencies:
  - arrow
  - bottleneck
  - cmocean
  - jupyterlab
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pip
  - python=3
  - pytz
  - scipy
  - xarray
